### ISSUE TITLE
1.7.0 熊拉仇恨时候，吃到减速就自动变形解，导致T深水领主时，一有减速图腾就变形。

### ISSUE THREAD

**Issue by tyrival** [alawing/WhitePaws#16]
#showtooltip 裂伤（熊）
/脚本 shift(0)
/施放 能量转化器
/施放 [form:1]裂伤（熊）;!巨熊形态
/脚本 wcEnd()
/startattack

**Comment by alawing** [comment]
之前考虑的是近战范围不自动解减速和定身，boss除外（为了防止坦克瓦斯琪不秒解）。准备把boss除外这个判断改成瓦斯琪除外，因为能打到boss的被定身需要秒解的情况只有瓦斯琪。

**Comment by alawing** [comment]
fixed with commit. Will release after few tests.
